In [ ]:
# Function definition is here
def changeme( mylist ):
   '''This changes a passed list into this function'''
   mylist = [1, 2, 3, 4] # This would assign new reference in mylist
   print("Values inside the function  : ", mylist)

# Now you can call changeme function
mylist = [10, 20, 30]
changeme( mylist )
print("Values outside the function : ", mylist)

In [ ]:
def fungsi_saya(p, 1):
    '''This changes a passed list into this function'''
    print(p*1)

fungsi_saya(5, 2)

In [ ]:
def luas_segitiga(alas, tinggi):
    luas= (alas* tinggi)/2
    print("luas segitiga= %.2f" %luas)

luas_segitiga(4,6)

##### __key word__

In [ ]:
def nama_orang(*nama):
    print('teman saya namanya:' + nama[3])
    
nama_orang("irfan", "tono", "joko","kondo")

In [ ]:
def printinfo( name = 'Tanpa Nama', age = 'Malu sama umur?' ):
   '''This prints a passed info into this function'''
   print("Name : ", name)
   print("Age  : ", age)
   print("")

# Now you can call printinfo function
printinfo( age=50, name="hacktiv8" )
printinfo( )

###### asterik

In [ ]:
def printinfo( arg1, *vartuple ): # aterik tanda (*)
# def printinfo(arg1, arg2, arg3, arg4):
   '''This prints a variable passed arguments'''
   print('arg1     : ', arg1)
   print('vartuple : ', vartuple)
   print('')
   
   for var in vartuple:
      print('isi vartuple : ', var) 

# Now you can call printinfo function
printinfo( 10 )
printinfo( 70, 60, 50, "a" )

In [ ]:
def person_car(total_data, **kwargs):
  '''Create a function to print who owns what car'''
  print('Total Data : ', total_data)
  for key, value in kwargs.items():
    print('Person : ', key)
    print('Car    : ', value)
    print('')

person_car(3, jimmy='chevrolet', frank='ford', tina='honda')
person_car(3)

In [ ]:
# Function definition is here
sum = lambda arg1, arg2: arg1 + arg2

# That lambda function will be equal to :
# def sum(arg1, arg2):
#     return arg1+arg2

# Now you can call sum as a function
print("Value of total : ", sum( 10, 20 ))
print("Value of total : ", sum( 20, 20 ))

In [ ]:
def hitung(x,y):
    return x**2+y**2
    
hitung(2,3)

In [ ]:
hitung = lambda x,y : x**2+y**2
hitung(2,3)

In [ ]:
def sum(arg1, arg2):
    # Add both the parameters and return them."
    total = arg1 + arg2
    return total

# Now you can call sum function
total = sum(10, 20)
print("Result function : ", total)

In [ ]:
nama = 'tomo'

def myfunc():
    nama = "broker"
    print('Saya adalah :', nama)
    
myfunc()

In [ ]:
nama = 'tomo'

def myfunc():
    nama = "broker"
    print('Saya adalah :', nama)
    
print('Saya adalah :', nama)

In [ ]:
import Lagi
print(Lagi.name)

In [ ]:
Lagi.devices

In [ ]:
from Lagi import name #tanpa perlu import devinisi "name" dari "Lagi"
name

In [ ]:
from Lagi import devices 
devices

In [ ]:
name

In [ ]:
devices

In [ ]:
import Lagi
print(Lagi.name)

In [ ]:
import Lagi
display('')

In [ ]:
from Lagi import name as n
n

In [ ]:
n

In [ ]:
!pip install pandas

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
a

In [ ]:
np.zeros(3)

In [ ]:
np.ones(2)

In [ ]:
np.empty(1)

In [ ]:
print(np.arange(4))
print(np.arange(1, 30, 20))

In [ ]:
print(np.arange(4))
print(np.arange(0,10,2)) # (start, stop, step)

In [ ]:
tinggi = [1.73, 1.68, 1.71, 1.86, 1.87]
berat = [65.4, 59.2, 63.2, 88.4, 68.7]
berat/tinggi**2 #Tanpa Array

In [ ]:
tinggi = [1.73, 1.68, 1.71, 1.86, 1.87]
berat = [65.4, 59.2, 63.2, 88.4, 68.7]
np_tinggi = np.array (tinggi)
np_berat = np.array (berat)
np_berat/np_tinggi**2

In [ ]:
arr= np.array([1, 2, 3, 4, 5])
np.append(arr, [6, 7, 8])

In [ ]:
panjang = np.array([1, 2, 4, 5])
lebar = np.array([4, 5, 5, 7])

luas= panjang*lebar
luas

In [ ]:
np.delete(arr, 3)

In [ ]:
array_1 = np.array ([[[1, 2, 3, 4],
                    [5, 6, 7, 8]],
                    
                    [[9, 10, 11, 12],
                    [11, 12, 13, 14]],
                   
                    [[15, 16, 17, 18],
                    [19, 20, 21, 22]]],)

array_1

In [ ]:
array_1.ndim

In [ ]:
array_1.size

In [ ]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

In [ ]:
a = np.arange(6)

print(a)

In [ ]:
b = a.reshape(3, 2)

print(b)

In [ ]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

In [ ]:
b = np.expand_dims(a, axis=1)
print(b)
b.shape

## _Latihan_

In [ ]:
import numpy as np
x = np.arange (2, 11).reshape(3, 3)
print(x)

In [ ]:
x.ndim

In [ ]:
arr = np.array(70)
print(arr)

In [ ]:
arr.ndim

In [ ]:
arr = np.array ([[[1, 2, 3], 
                  [4, 5, 6], 
                  [4, 5, 6]]])
print(arr)
arr.shape
arr.ndim

In [ ]:
arr.shape

In [ ]:
array_tes = np.array([[3, 7, 10, 2], [3, 7, 10, 2]], ndmin=4)
print(array_tes)

In [ ]:
array_tes.ndim

In [ ]:
array_tes = np.array ([3, 10, 3, 2])

print(array_tes[3] + array_tes[2])

In [23]:

arr = np.array([[6, 7, 8, 9, 10],[1, 2, 3, 4, 5]])
print(arr[1, 1])

2


In [2]:
import numpy as np
jiwa = np.array ([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

print(jiwa[:, 1, 2])
print(jiwa.shape)

[ 6 12]
(2, 2, 3)


In [16]:
print(jiwa[:1, :2, 1])

[[2 5]]


In [26]:
arr = np.array([2, 2, 7, 4, 5, 6, 7, 8, 10])
print(arr[2:10:3]) 
print(arr[::3])

[ 7  6 10]
[2 4 7]


In [34]:
arr = np.array ([1, 2, 3, 4, 5, 6, 7, 8, 9 ,10, 11, 12])
newarr= arr.reshape(1, 2, -1)
print(newarr, "\n")
print(newarr.shape)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]] 

(1, 2, 6)
